# File: .github/workflows/nginxForAzureDeploy.yml

name: Sync the NGINX configuration from the Git repository to an NGINX for Azure deployment
on:
  push:
    branches:
      - main
    paths:
      - etc/nginx/**
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME: jcox-rg
  NGINX_DEPLOYMENT_NAME: jcox-instance-nginx-1

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-NGINX-Configuration:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2

    - name: 'Run Azure Login using Azure Service Principal with a secret'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Sync the NGINX configuration from the Git repository to the NGINX for Azure deployment'
      uses: nginxinc/nginx-for-azure-deploy-action@v1
      with:
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group-name: $AZURE_RESOURCE_GROUP_NAME
        nginx-deployment-name: $NGINX_DEPLOYMENT_NAME
        nginx-config-directory-path: /etc/nginx/
        nginx-root-config-file: nginx.conf
        transformed-nginx-config-directory-path: /etc/nginx/